version: '3.9'

services:
  db:
    container_name: db
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ewallet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - ./internal/database:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
  
  app:
    container_name: app
    build: .
    environment:
      - PGHOST=db
      - PGDATABASE=ewallet
      - PGUSER=postgres
      - PGPASSWORD=postgres
    ports:
      - "8000:8000"
    restart: on-failure:10
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

volumes:  
  pgdata: {}
